import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { readCms } from "@/lib/cms";
import { catalog } from "@/lib/catalog";
import SitePage from "../components/site-page";
export const dynamic = "force-dynamic";
const pages:Record<string,string>={solucoes:"Serviços e Produtos",segmentos:"Segurança para Casas, Condomínios e Empresas",cidades:"Atendimento em Balneário Camboriú",projetos:"Projetos de Segurança Eletrônica",blog:"Blog de Segurança Eletrônica",sobre:"Sobre a Monitore",contato:"Solicitar Orçamento"};
export async function generateMetadata({params}:{params:Promise<{slug?:string[]}>}):Promise<Metadata>{const {slug=[]}=await params;const cms=await readCms();const service=catalog.find(s=>s.slug===slug[0]);const post=slug[0]==="blog"&&slug[1]?cms.posts.find(p=>p.slug===slug[1]):undefined;const title=service?`${service.name} em Balneário Camboriú`:post?(post.seoTitle||post.title):pages[slug[0]]||cms.seo.title;const description=service?service.desc:post?(post.seoDescription||post.excerpt):cms.seo.description;const url=`/${slug.join("/")}`;return {title,description,alternates:{canonical:url},openGraph:{title,description,url,locale:"pt_BR",images:[service?.image||post?.image||"/monitore-hero.jpg"]}};}
export default async function Page({params}:{params:Promise<{slug?:string[]}>}){const {slug=[]}=await params;const cms=await readCms();if(slug.length&&!(slug.length===1&&(pages[slug[0]]||cms.services.some(s=>s.slug===slug[0]&&s.published!==false)))&&!(slug[0]==="cidades"&&slug[1]==="balneario-camboriu"&&slug.length===2)&&!(slug[0]==="blog"&&slug.length===2&&cms.posts.some(p=>p.slug===slug[1]&&(p.status==="published"||p.status==="scheduled"&&new Date(p.publishAt).getTime()<=Date.now()))))notFound();const schema={"@context":"https://schema.org","@type":"LocalBusiness",name:cms.company.name,url:"https://www.monitorecbc.com.br",telephone:cms.company.phone,image:"https://www.monitorecbc.com.br/logo-monitore-nova.png",address:{"@type":"PostalAddress",streetAddress:cms.company.address,addressLocality:"Balneário Camboriú",addressRegion:"SC",postalCode:cms.company.postalCode,addressCountry:"BR"},areaServed:"Balneário Camboriú",hasOfferCatalog:{"@type":"OfferCatalog",name:"Serviços e produtos Monitore",itemListElement:cms.services.filter(s=>s.published!==false).map(s=>({"@type":"Offer",itemOffered:{"@type":s.kind==="produto"?"Product":"Service",name:s.name,description:s.desc,url:`https://www.monitorecbc.com.br/${s.slug}`}}))}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\u003c")}}/><SitePage slug={slug} initialSite={{company:cms.company,home:cms.home,seo:cms.seo,services:cms.services,posts:cms.posts}}/></>;}
