"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { Menu, X, Phone, MapPin, ArrowRight, Check, ShieldCheck, Network, Building2, House, Factory, ChevronRight } from "lucide-react";

const services = [
  {slug:"cameras-de-seguranca-cftv",name:"Câmeras de Segurança e CFTV",image:"/services/cftv.jpg",desc:"Projetos de CFTV com câmeras estrategicamente posicionadas, gravação confiável e acesso remoto para ampliar a visibilidade do imóvel.",benefits:["Cobertura planejada","Gravação e consulta","Acesso remoto"]},
  {slug:"alarmes-e-sensores",name:"Alarmes e Sensores",image:"/services/alarmes.jpg",desc:"Sistemas com sensores e central inteligente, configurados conforme acessos, ambientes e prioridades de proteção.",benefits:["Detecção de eventos","Configuração por ambiente","Integração ao projeto"]},
  {slug:"controle-de-acesso",name:"Controle de Acesso",image:"/services/controle-acesso.jpg",desc:"Organização e proteção do fluxo de pessoas por biometria, cartão, senha ou soluções digitais adequadas ao contexto.",benefits:["Entradas organizadas","Mais rastreabilidade","Gestão de permissões"]},
  {slug:"automacao",name:"Automação",image:"/services/automacao.jpg",desc:"Integração de iluminação, climatização, segurança e equipamentos para proporcionar praticidade e controle.",benefits:["Rotinas inteligentes","Controle centralizado","Mais praticidade"]},
  {slug:"cerca-eletrica",name:"Cerca Elétrica",image:"/services/cerca-eletrica.jpg",desc:"Proteção perimetral dimensionada para o imóvel, com instalação cuidadosa e integração ao sistema de segurança.",benefits:["Proteção perimetral","Projeto contextual","Integração com alarmes"]},
  {slug:"iluminacao-de-emergencia",name:"Iluminação de Emergência",image:"/services/iluminacao-emergencia.jpg",desc:"Soluções para rotas de saída, corredores e áreas comuns, favorecendo orientação durante quedas de energia.",benefits:["Rotas mais visíveis","Cobertura de áreas comuns","Planejamento técnico"]},
  {slug:"energia-solar",name:"Energia Solar",image:"/services/energia-solar.jpg",desc:"Projeto de geração fotovoltaica organizado conforme o imóvel e a necessidade energética apresentada.",benefits:["Geração renovável","Projeto sob medida","Acompanhamento claro"]},
  {slug:"armarios-inteligentes",name:"Armários Inteligentes",image:"/services/armarios-inteligentes.jpg",desc:"Estrutura tecnológica para recebimento e retirada organizada de encomendas em condomínios e empresas.",benefits:["Retirada organizada","Mais autonomia","Operação simplificada"]},
  {slug:"carregadores-veiculos-eletricos",name:"Carregadores para Veículos Elétricos",image:"/services/carregadores-ve.jpg",desc:"Infraestrutura de recarga preparada de acordo com o local, a demanda e as condições técnicas disponíveis.",benefits:["Recarga conveniente","Infraestrutura planejada","Uso residencial ou corporativo"]},
  {slug:"sonorizacao",name:"Sonorização de Ambientes",image:"/services/sonorizacao.jpg",desc:"Distribuição de áudio pensada para ambientes residenciais, comerciais e corporativos, com integração discreta.",benefits:["Som bem distribuído","Integração ao ambiente","Controle simplificado"]},
  {slug:"interfonia-video-porteiro",name:"Interfonia e Vídeo Porteiro",image:"/services/interfonia.jpg",desc:"Comunicação e visualização de acessos para apoiar uma entrada mais organizada e segura.",benefits:["Identificação de visitantes","Comunicação direta","Mais controle na entrada"]},
  {slug:"cabeamento-redes",name:"Cabeamento Estruturado e Redes",image:"/services/cabeamento.jpg",desc:"Infraestrutura organizada para dados, conectividade e equipamentos, planejada para estabilidade e expansão.",benefits:["Rede organizada","Conectividade estável","Expansão facilitada"]},
  {slug:"automatizadores-portoes",name:"Automatizadores de Portões",image:"/services/portoes.jpg",desc:"Automação de acessos veiculares com solução dimensionada conforme portão, fluxo e necessidade do imóvel.",benefits:["Acesso mais prático","Operação automatizada","Projeto por contexto"]},
  {slug:"monitoramento",name:"Monitoramento",image:"/services/monitoramento.jpg",desc:"Estrutura integrada para acompanhamento de eventos e equipamentos de segurança eletrônica.",benefits:["Acompanhamento centralizado","Integração de sistemas","Mais visibilidade operacional"]}
];

const nav = [["Soluções","/solucoes"],["Segmentos","/segmentos"],["Cidades","/cidades"],["Projetos","/projetos"],["Blog","/blog"],["Sobre","/sobre"],["Contato","/contato"]];

function Header(){const [open,setOpen]=useState(false);return <><header className="header"><Link href="/" className="brand"><Image src="/logo-monitore-nova.png" alt="Monitore Sistemas Eletrônicos" width={250} height={92} priority/></Link><nav>{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</nav><Link className="btn small" href="/contato#orcamento">Solicitar orçamento</Link><button className="menu" aria-label="Abrir menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobile"><Image src="/logo-monitore-nova.png" alt="Monitore Sistemas Eletrônicos" width={230} height={85}/>{nav.map(([n,h])=><Link key={h} href={h} onClick={()=>setOpen(false)}>{n}<ChevronRight size={17}/></Link>)}<Link className="btn" href="/contato#orcamento">Solicitar orçamento</Link></div>}</>}
function Footer(){return <footer><div className="footer-grid"><div><Image src="/logo-monitore-nova.png" alt="Monitore Sistemas Eletrônicos" width={260} height={96}/><p>Soluções em segurança eletrônica e tecnologia, com atendimento a partir de Balneário Camboriú.</p></div><div><strong>Navegação</strong>{nav.slice(0,5).map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><strong>Contato oficial</strong><a href="tel:+554733653287">(47) 3365-3287</a><span>5ª Avenida, 185 — Vila Real</span><span>Balneário Camboriú – SC</span><span>CEP 88330-260</span></div></div><div className="legal"><span>Monitore Sistemas Eletrônicos • CNPJ 07.034.637/0001-48</span><span>Dados oficiais fornecidos pela empresa.</span></div></footer>}
function CTA(){return <section className="cta"><div><span className="eyebrow light">Vamos conversar?</span><h2>Precisa de um projeto de segurança eletrônica?</h2><p>Conte sua necessidade para a equipe da Monitore.</p></div><Link className="btn white" href="/contato#orcamento">Solicitar orçamento <ArrowRight size={18}/></Link></section>}
function ServiceCard({s}:{s:typeof services[0]}){return <article className="service-card"><Link href={`/solucoes/${s.slug}`} className="card-image"><Image src={s.image} alt={s.name} fill sizes="(max-width: 720px) 100vw, 33vw"/></Link><div className="card-copy"><span className="card-kicker">Solução Monitore</span><h3>{s.name}</h3><p>{s.desc}</p><ul>{s.benefits.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><div className="card-actions"><Link href={`/contato?servico=${encodeURIComponent(s.name)}#orcamento`} className="btn small">Solicitar orçamento</Link><Link href={`/solucoes/${s.slug}`} className="text-link">Ver detalhes <ArrowRight size={16}/></Link></div></div></article>}
function Hero(){return <section className="hero"><Image src="/monitore-hero.jpg" alt="Profissional configurando sistema de segurança eletrônica" fill priority sizes="100vw"/><div className="hero-overlay"/><div className="hero-copy"><span className="eyebrow light">Tecnologia aplicada à proteção</span><h1>Segurança eletrônica e tecnologia em <em>Balneário Camboriú</em></h1><p>Projetos pensados para o contexto de cada imóvel, com atendimento próximo e uma jornada clara do primeiro contato à execução.</p><div className="hero-actions"><Link className="btn" href="/contato#orcamento">Solicitar orçamento</Link><a className="btn ghost" href="tel:+554733653287"><Phone size={18}/> Falar com especialista</a></div></div></section>}
function Home(){return <><Hero/><section className="facts"><div><b>(47) 3365-3287</b><span>Telefone oficial</span></div><div><b>Vila Real</b><span>Balneário Camboriú</span></div><div><b>07.034.637/0001-48</b><span>CNPJ</span></div></section><section className="section"><span className="eyebrow">Soluções Monitore</span><h2>Proteção e tecnologia para cada necessidade.</h2><p className="lead">Serviços apresentados com imagem própria, benefícios e acesso direto ao orçamento.</p><div className="services-grid">{services.slice(0,6).map(s=><ServiceCard key={s.slug} s={s}/>)}</div><div className="center"><Link className="btn dark" href="/solucoes">Ver todas as soluções <ArrowRight size={18}/></Link></div></section><section className="split dark-section"><div><span className="eyebrow light">Soluções sob medida</span><h2>Um projeto começa pelo diagnóstico certo.</h2><p>Entendimento do imóvel, dos fluxos e das prioridades antes da proposta.</p><div className="steps">{[["01","Leitura do cenário"],["02","Projeto contextual"],["03","Execução orientada"]].map(([n,t])=><div key={n}><b>{n}</b><span>{t}</span></div>)}</div></div><div className="feature-image"><Image src="/services/controle-acesso.jpg" alt="Controle de acesso moderno" fill/></div></section><section className="section"><span className="eyebrow">Projetado para pessoas reais</span><h2>Segurança deve simplificar a rotina.</h2><div className="audiences">{[[Building2,"Condomínios","Gestão compartilhada"],[Factory,"Empresas","Continuidade operacional"],[House,"Residências","Proteção cotidiana"]].map(([Icon,t,s]:any)=><article key={t}><Icon/><span>{s}</span><h3>{t}</h3><p>Informação organizada e uma jornada clara para cada contexto.</p></article>)}</div></section><section className="local"><div className="feature-image"><Image src="/services/cftv.jpg" alt="Instalação profissional de CFTV" fill/></div><div><span className="eyebrow">Presença local confirmada</span><h2>Monitore em Balneário Camboriú.</h2><p>5ª Avenida, 185 — Vila Real<br/>Balneário Camboriú – SC<br/>CEP 88330-260</p><Link className="text-link" href="/cidades/balneario-camboriu">Conhecer a página local <ArrowRight size={16}/></Link></div></section><CTA/></>}
function Solutions(){return <><PageHero title="Tecnologia para proteger, conectar e simplificar." text="Encontre a solução adequada ao contexto do seu imóvel." image="/services/automacao.jpg"/><section className="section"><span className="eyebrow">Portfólio de soluções</span><h2>Serviços com contexto, benefícios e acesso direto ao orçamento.</h2><div className="services-grid">{services.map(s=><ServiceCard key={s.slug} s={s}/>)}</div></section><CTA/></>}
function PageHero({title,text,image}:{title:string,text:string,image:string}){return <section className="page-hero"><Image src={image} alt="" fill priority/><div className="hero-overlay"/><div><span className="eyebrow light">Monitore Sistemas Eletrônicos</span><h1>{title}</h1><p>{text}</p></div></section>}
function StandardPage({kind}:{kind:string}){const data:any={segmentos:["Soluções pensadas para cada contexto de decisão.","Residências, condomínios e empresas têm fluxos diferentes. A Monitore organiza cada projeto conforme a necessidade apresentada.","/services/interfonia.jpg"],sobre:["Monitore Sistemas Eletrônicos.","Atendimento a partir de Balneário Camboriú com foco em segurança eletrônica, conectividade e tecnologia aplicada aos imóveis.","/services/cftv.jpg"],projetos:["Projetos organizados com contexto.","Esta área está preparada para receber projetos reais após validação e autorização da empresa, sem inventar clientes, resultados ou avaliações.","/services/cabeamento.jpg"],cidades:["Presença local com informação confirmada.","A página utiliza somente Balneário Camboriú, endereço oficial fornecido pela empresa. Novas cidades não são publicadas sem confirmação.","/services/portoes.jpg"],blog:["Conteúdo que ajuda a decidir melhor.","Guias sobre segurança, automação, redes e tecnologia, organizados para responder dúvidas antes da solicitação de orçamento.","/services/monitoramento.jpg"]};const [title,text,image]=data[kind];return <><PageHero title={title} text={text} image={image}/><section className="section"><div className="content-grid"><div><span className="eyebrow">Informação clara</span><h2>{kind==="sobre"?"Identidade, localização e compromisso.":"Uma estrutura preparada para crescer com dados reais."}</h2><p className="lead">{text}</p><p>Telefone oficial: <a href="tel:+554733653287">(47) 3365-3287</a><br/>5ª Avenida, 185 — Vila Real, Balneário Camboriú – SC.</p><Link className="btn dark" href="/contato#orcamento">Solicitar orçamento</Link></div><div className="stack-images"><Image src={image} alt={title} fill/></div></div></section>{kind==="segmentos"&&<section className="section alt"><div className="audiences">{[[Building2,"Condomínios"],[Factory,"Empresas"],[House,"Residências"]].map(([Icon,t]:any)=><article key={t}><Icon/><h3>{t}</h3><p>Soluções organizadas conforme o uso e o ambiente.</p></article>)}</div></section>}{kind==="blog"&&<section className="section alt"><h2>Temas em preparação</h2><div className="post-grid">{["Como planejar um sistema de CFTV","Controle de acesso em condomínios","Cabeamento estruturado e redes"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Conteúdo editorial em preparação, sem alegações ainda não validadas.</p></article>)}</div></section>}<CTA/></>}
function ServicePage({slug}:{slug:string}){const s=services.find(x=>x.slug===slug);if(!s)return <Solutions/>;return <><PageHero title={s.name} text={s.desc} image={s.image}/><section className="section"><div className="content-grid"><div><span className="eyebrow">Solução Monitore</span><h2>Projeto organizado para a sua necessidade.</h2><p className="lead">{s.desc}</p><h3>Principais benefícios</h3><ul className="benefit-list">{s.benefits.map(x=><li key={x}><ShieldCheck/>{x}</li>)}</ul><Link className="btn" href={`/contato?servico=${encodeURIComponent(s.name)}#orcamento`}>Solicitar orçamento</Link></div><div className="stack-images"><Image src={s.image} alt={s.name} fill/></div></div></section><CTA/></>}
function Contact(){return <><PageHero title="Fale com a Monitore." text="Solicite uma avaliação pelo formulário ou telefone oficial." image="/services/controle-acesso.jpg"/><section className="section contact" id="orcamento"><div><span className="eyebrow">Contato oficial</span><h2>Conte o que você precisa.</h2><a className="contact-line" href="tel:+554733653287"><Phone/> (47) 3365-3287</a><p><MapPin size={19}/> 5ª Avenida, 185 — Vila Real<br/>Balneário Camboriú – SC — CEP 88330-260</p><small>Não publicamos WhatsApp, e-mail ou horários não confirmados.</small></div><form><label>Nome<input required placeholder="Como podemos chamar você?"/></label><label>Telefone<input required placeholder="(47) 99999-9999"/></label><label>Cidade<input required defaultValue="Balneário Camboriú"/></label><label>Necessidade<textarea rows={5} placeholder="Descreva a solução que procura"/></label><button className="btn" type="button">Enviar solicitação</button><small>O envio será ativado após a confirmação do canal de recebimento pela empresa.</small></form></section></>}
export default function Page({params}:{params:Promise<{slug?:string[]}>}){const React=require("react");const {slug=[]}=React.use(params);let content:any=<Home/>;if(slug[0]==="solucoes"&&slug[1])content=<ServicePage slug={slug[1]}/>;else if(slug[0]==="solucoes")content=<Solutions/>;else if(["segmentos","sobre","projetos","cidades","blog"].includes(slug[0]))content=<StandardPage kind={slug[0]}/>;else if(slug[0]==="contato")content=<Contact/>;else if(slug[0]==="cidades"&&slug[1])content=<StandardPage kind="cidades"/>;return <><Header/><main>{content}</main><Footer/><div className="mobile-cta"><a href="tel:+554733653287"><Phone size={18}/>Ligar</a><Link href="/contato#orcamento">Orçamento</Link></div></>}
