"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Building2, FileText, ImageIcon, LayoutDashboard, LogOut, Save, Search, Settings, ShieldCheck, Users } from "lucide-react";
type Cms = { company: Record<string,string>; home: Record<string,string>; seo: Record<string,string>; updatedAt?: string|null; updatedBy?: string|null };
export default function AdminPage() {
  const [email,setEmail]=useState(""); const [code,setCode]=useState(""); const [step,setStep]=useState<"email"|"code"|"panel">("email"); const [cms,setCms]=useState<Cms|null>(null); const [session,setSession]=useState<any>(null); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch("/api/admin/content");if(r.ok){const d=await r.json();setCms(d.content);setSession(d.session);setStep("panel");}}
  useEffect(()=>{load()},[]);
  async function requestCode(){setBusy(true);setNotice("");const r=await fetch("/api/admin/request-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json();setBusy(false);if(r.ok){setStep("code");setNotice("Código enviado para o seu e-mail.")}else setNotice(d.error);}
  async function verify(){setBusy(true);const r=await fetch("/api/admin/verify-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,token:code})});const d=await r.json();setBusy(false);if(r.ok)await load();else setNotice(d.error);}
  async function save(){if(!cms)return;setBusy(true);setNotice("");try{const r=await fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(cms)});const d=await r.json();setNotice(r.ok?"Alterações salvas com segurança.":d.error||"Não foi possível salvar.");if(r.ok)setCms(d.content);}catch{setNotice("A conexão falhou. Tente novamente em instantes.");}finally{setBusy(false);}}
  function field(group:"company"|"home"|"seo",key:string,label:string){return <label className="admin-field"><span>{label}</span><input value={cms?.[group]?.[key]||""} onChange={e=>setCms(cms?{...cms,[group]:{...cms[group],[key]:e.target.value}}:cms)}/></label>}
  if(step!=="panel")return <main className="admin-login"><section><Image src="/logo-monitore-nova.png" alt="Monitore" width={250} height={92}/><span className="admin-badge"><ShieldCheck size={16}/> Painel protegido</span><h1>{step==="email"?"Acesse a administração":"Digite o código recebido"}</h1><p>Use uma das contas autorizadas para gerenciar o site.</p>{step==="email"?<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></label>:<label>Código de acesso<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)} placeholder="000000"/></label>}<button className="admin-primary" disabled={busy} onClick={step==="email"?requestCode:verify}>{busy?"Aguarde...":step==="email"?"Enviar código seguro":"Entrar no painel"}</button>{notice&&<p className="admin-notice">{notice}</p>}<small>Nunca solicitaremos sua senha por telefone ou mensagem.</small></section></main>;
  return <main className="admin-shell"><aside><Image src="/logo-monitore-nova.png" alt="Monitore" width={210} height={78}/><nav>{[[LayoutDashboard,"Visão geral"],[Building2,"Empresa"],[FileText,"Páginas e serviços"],[ImageIcon,"Imagens"],[Search,"SEO"],[Users,"Usuários"],[Settings,"Configurações"]].map(([Icon,label]:any,i)=><button key={label} className={i===0?"active":""}><Icon size={19}/>{label}</button>)}</nav><button className="admin-logout" onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});location.reload()}}><LogOut size={18}/>Sair</button></aside><section className="admin-main"><header><div><span>Administração Monitore</span><h1>Olá, {session?.role==="superadmin"?"responsável técnico":"administrador"}.</h1></div><button className="admin-primary compact" onClick={save} disabled={busy}><Save size={17}/>{busy?"Salvando...":"Salvar alterações"}</button></header><div className="admin-cards"><article><span>Perfil de acesso</span><b>{session?.role==="superadmin"?"Superadministrador técnico":"Administrador de conteúdo"}</b><small>{session?.email}</small></article><article><span>Usuários iniciais</span><b>2 contas</b><small>Permissões independentes</small></article><article><span>Última alteração</span><b>{cms?.updatedAt?new Date(cms.updatedAt).toLocaleDateString("pt-BR"):"Nenhuma"}</b><small>{cms?.updatedBy||"Conteúdo original"}</small></article></div><div className="admin-panel"><span className="admin-kicker">Dados oficiais</span><h2>Informações da empresa</h2><div className="admin-grid">{field("company","name","Nome da empresa")}{field("company","phone","Telefone")}{field("company","address","Endereço")}{field("company","city","Cidade / Estado")}{field("company","postalCode","CEP")}{field("company","cnpj","CNPJ")}</div></div><div className="admin-panel"><span className="admin-kicker">Página inicial</span><h2>Apresentação principal</h2><div className="admin-grid one">{field("home","title","Título principal")}{field("home","description","Descrição comercial")}</div></div><div className="admin-panel"><span className="admin-kicker">Google e compartilhamento</span><h2>SEO principal</h2><div className="admin-grid one">{field("seo","title","Título SEO")}{field("seo","description","Descrição SEO")}</div></div>{notice&&<div className="admin-toast">{notice}</div>}</section></main>;
}
