"use client";
import Image from "next/image";
import { useEffect,useState } from "react";
import { Activity,ArrowDown,ArrowUp,Building2,CheckCircle2,Copy,ExternalLink,FileText,ImageIcon,LayoutDashboard,LogOut,Plus,Save,Search,Settings,ShieldCheck,Trash2,Upload,Users } from "lucide-react";
type Service={slug:string;name:string;image:string;desc:string;benefits:string[];published:boolean};
type Cms={company:Record<string,string>;home:Record<string,string>;seo:Record<string,string>;services:Service[];updatedAt?:string|null;updatedBy?:string|null};
type Section="overview"|"company"|"pages"|"images"|"seo"|"users"|"settings";
type MediaFile={name:string;path:string;url:string;created_at?:string;metadata?:{size?:number;mimetype?:string}};
export default function AdminPage(){
 const [email,setEmail]=useState(""),[code,setCode]=useState(""),[step,setStep]=useState<"email"|"code"|"panel">("email"),[cms,setCms]=useState<Cms|null>(null),[session,setSession]=useState<any>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[section,setSection]=useState<Section>("overview"),[media,setMedia]=useState<MediaFile[]>([]),[mediaBusy,setMediaBusy]=useState(false);
 async function load(){const r=await fetch("/api/admin/content");if(r.ok){const d=await r.json();setCms({...d.content,services:Array.isArray(d.content.services)?d.content.services:[]});setSession(d.session);setStep("panel")}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(section==="images")loadMedia()},[section]);
 async function requestCode(){setBusy(true);setNotice("");const r=await fetch("/api/admin/request-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}),d=await r.json();setBusy(false);if(r.ok){setStep("code");setNotice("Código enviado para o seu e-mail.")}else setNotice(d.error)}
 async function verify(){setBusy(true);const r=await fetch("/api/admin/verify-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,token:code})}),d=await r.json();setBusy(false);if(r.ok)await load();else setNotice(d.error)}
 async function save(){if(!cms)return;setBusy(true);setNotice("");try{const r=await fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(cms)}),d=await r.json();setNotice(r.ok?"Alterações salvas e publicadas no site.":d.error||"Não foi possível salvar.");if(r.ok)setCms(d.content)}catch{setNotice("A conexão falhou. Tente novamente em instantes.")}finally{setBusy(false)}}
 function field(group:"company"|"home"|"seo",key:string,label:string){return <label className="admin-field"><span>{label}</span><input value={cms?.[group]?.[key]||""} onChange={e=>setCms(cms?{...cms,[group]:{...cms[group],[key]:e.target.value}}:cms)}/></label>}
 function updateService(i:number,patch:Partial<Service>){if(!cms)return;const services=[...cms.services];services[i]={...services[i],...patch};setCms({...cms,services})}
 function moveService(i:number,d:number){if(!cms||i+d<0||i+d>=cms.services.length)return;const services=[...cms.services];[services[i],services[i+d]]=[services[i+d],services[i]];setCms({...cms,services})}
 function addService(){if(cms)setCms({...cms,services:[...cms.services,{name:"Nova solução",slug:`nova-solucao-${cms.services.length+1}`,image:"/services/cftv.jpg",desc:"Descrição comercial da solução.",benefits:["Benefício principal"],published:false}]})}
 function removeService(i:number){if(cms&&confirm("Remover esta solução do painel?"))setCms({...cms,services:cms.services.filter((_,n)=>n!==i)})}
 async function openSection(id:Section){setSection(id);if(id==="images")await loadMedia()}
 async function loadMedia(){setMediaBusy(true);try{const r=await fetch("/api/admin/media"),d=await r.json();if(r.ok)setMedia(d.files||[]);else setNotice(d.error)}finally{setMediaBusy(false)}}
 async function uploadMedia(file?:File){if(!file)return;setMediaBusy(true);setNotice("");try{const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/media",{method:"POST",body:form}),d=await r.json();setNotice(r.ok?"Imagem enviada para a biblioteca.":d.error);if(r.ok)await loadMedia()}catch{setNotice("Falha ao enviar a imagem.")}finally{setMediaBusy(false)}}
 async function deleteMedia(file:MediaFile){if(!confirm("Excluir esta imagem permanentemente?"))return;const r=await fetch("/api/admin/media",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:file.path})}),d=await r.json();setNotice(r.ok?"Imagem excluída.":d.error);if(r.ok)await loadMedia()}
 async function copyUrl(url:string){await navigator.clipboard.writeText(url);setNotice("Endereço da imagem copiado.")}
 if(step!=="panel")return <main className="admin-login"><section><Image src="/logo-monitore-nova.png" alt="Monitore" width={250} height={92}/><span className="admin-badge"><ShieldCheck size={16}/> Painel protegido</span><h1>{step==="email"?"Acesse a administração":"Digite o código recebido"}</h1><p>Use uma das contas autorizadas para gerenciar o site.</p>{step==="email"?<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></label>:<label>Código de acesso<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)} placeholder="000000"/></label>}<button className="admin-primary" disabled={busy} onClick={step==="email"?requestCode:verify}>{busy?"Aguarde...":step==="email"?"Enviar código seguro":"Entrar no painel"}</button>{notice&&<p className="admin-notice">{notice}</p>}<small>Nunca solicitaremos sua senha por telefone ou mensagem.</small></section></main>;
 const modules:Array<[any,string,Section]>=[[LayoutDashboard,"Visão geral","overview"],[Building2,"Empresa","company"],[FileText,"Páginas e serviços","pages"],[ImageIcon,"Imagens","images"],[Search,"SEO","seo"],[Users,"Usuários","users"],[Settings,"Configurações","settings"]];
 return <main className="admin-shell"><aside><Image src="/logo-monitore-nova.png" alt="Monitore" width={210} height={78}/><nav>{modules.map(([Icon,label,id])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon size={19}/>{label}</button>)}</nav><button className="admin-logout" onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});location.reload()}}><LogOut size={18}/>Sair</button></aside><section className="admin-main"><header><div><span>Administração Monitore</span><h1>{section==="pages"?"Páginas e serviços":section==="company"?"Dados da empresa":section==="seo"?"SEO do site":section==="users"?"Usuários":`Olá, ${session?.role==="superadmin"?"responsável técnico":"administrador"}.`}</h1></div><button className="admin-primary compact" onClick={save} disabled={busy}><Save size={17}/>{busy?"Salvando...":"Salvar alterações"}</button></header>
 {section==="overview"&&<><div className="admin-cards"><article><span>Perfil de acesso</span><b>{session?.role==="superadmin"?"Superadministrador técnico":"Administrador de conteúdo"}</b><small>{session?.email}</small></article><article><span>Soluções cadastradas</span><b>{cms?.services.length||0} serviços</b><small>{cms?.services.filter(s=>s.published).length||0} publicados</small></article><article><span>Última alteração</span><b>{cms?.updatedAt?new Date(cms.updatedAt).toLocaleDateString("pt-BR"):"Nenhuma"}</b><small>{cms?.updatedBy||"Conteúdo original"}</small></article></div><div className="admin-panel"><span className="admin-kicker">Página inicial</span><h2>Apresentação principal</h2><div className="admin-grid one">{field("home","title","Título principal")}{field("home","description","Descrição comercial")}</div></div></>}
 {section==="company"&&<div className="admin-panel"><span className="admin-kicker">Dados oficiais</span><h2>Informações da empresa</h2><div className="admin-grid">{field("company","name","Nome da empresa")}{field("company","phone","Telefone")}{field("company","address","Endereço")}{field("company","city","Cidade / Estado")}{field("company","postalCode","CEP")}{field("company","cnpj","CNPJ")}</div></div>}
 {section==="pages"&&<><div className="admin-toolbar"><div><span className="admin-kicker">Portfólio público</span><p>Edite, ordene e publique as soluções exibidas no site.</p></div><button className="admin-secondary" onClick={addService}><Plus size={17}/>Adicionar solução</button></div><div className="service-editor-list">{cms?.services.map((s,i)=><article className="service-editor" key={`${s.slug}-${i}`}><div className="service-editor-head"><b>{i+1}. {s.name}</b><div><label className="publish-toggle"><input type="checkbox" checked={s.published} onChange={e=>updateService(i,{published:e.target.checked})}/><span>{s.published?"Publicado":"Rascunho"}</span></label><button title="Mover para cima" onClick={()=>moveService(i,-1)} disabled={i===0}><ArrowUp size={17}/></button><button title="Mover para baixo" onClick={()=>moveService(i,1)} disabled={i===cms.services.length-1}><ArrowDown size={17}/></button><button className="danger" title="Excluir" onClick={()=>removeService(i)}><Trash2 size={17}/></button></div></div><div className="admin-grid"><label className="admin-field"><span>Nome do serviço</span><input value={s.name} onChange={e=>updateService(i,{name:e.target.value})}/></label><label className="admin-field"><span>Endereço da página (slug)</span><input value={s.slug} onChange={e=>updateService(i,{slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-")})}/></label><label className="admin-field full"><span>Descrição comercial</span><textarea rows={3} value={s.desc} onChange={e=>updateService(i,{desc:e.target.value})}/></label><label className="admin-field"><span>Imagem</span><input value={s.image} onChange={e=>updateService(i,{image:e.target.value})}/></label><label className="admin-field"><span>Benefícios (um por linha)</span><textarea rows={3} value={s.benefits.join("\n")} onChange={e=>updateService(i,{benefits:e.target.value.split("\n").filter(Boolean)})}/></label></div></article>)}</div></>}
 {section==="images"&&<><div className="admin-toolbar media-toolbar"><div><span className="admin-kicker">Biblioteca visual</span><h2>Imagens do site</h2><p>Envie arquivos otimizados e copie o endereço para usar em qualquer serviço.</p></div><label className="admin-secondary upload-button"><Upload size={17}/>{mediaBusy?"Processando...":"Enviar imagem"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/svg+xml" disabled={mediaBusy} onChange={e=>uploadMedia(e.target.files?.[0])}/></label></div><div className="media-summary"><span><ImageIcon size={18}/><b>{media.length}</b> arquivos na biblioteca</span><span><ShieldCheck size={18}/>JPG, PNG, WebP, GIF ou SVG — até 5 MB</span></div>{mediaBusy&&!media.length?<div className="admin-empty">Carregando biblioteca...</div>:media.length?<div className="media-grid">{media.map(file=><article key={file.path}><div className="media-preview" style={{backgroundImage:`url(${file.url})`}}/><div className="media-copy"><b title={file.name}>{file.name.replace(/^\d+-/,"")}</b><small>{file.metadata?.size?`${(file.metadata.size/1024).toFixed(0)} KB`:"Imagem"}</small><div><button onClick={()=>copyUrl(file.url)}><Copy size={15}/>Copiar URL</button><a href={file.url} target="_blank" rel="noreferrer" title="Abrir imagem"><ExternalLink size={15}/></a>{session?.role==="superadmin"&&<button className="danger" onClick={()=>deleteMedia(file)} title="Excluir imagem"><Trash2 size={15}/></button>}</div></div></article>)}</div>:<div className="admin-empty"><ImageIcon size={35}/><b>Nenhuma imagem enviada ainda</b><span>Use “Enviar imagem” para iniciar sua biblioteca.</span></div>}</>}
 {section==="seo"&&<div className="admin-panel"><span className="admin-kicker">Google e compartilhamento</span><h2>SEO principal</h2><div className="admin-grid one">{field("seo","title","Título SEO")}{field("seo","description","Descrição SEO")}</div></div>}
 {section==="users"&&<div className="admin-panel"><span className="admin-kicker">Acessos autorizados</span><h2>Usuários iniciais</h2><div className="user-list"><article><b>balneariocamboriuparcerias@gmail.com</b><span>Superadministrador técnico</span></article><article><b>monitoresystem@hotmail.com</b><span>Administrador de conteúdo</span></article></div></div>}
 {section==="settings"&&<Info kicker="Segurança" title="Configurações do painel" text="Login por código temporário, banco Supabase e publicação do conteúdo estão ativos. Somente contas autorizadas podem acessar."/>}
 {notice&&<div className="admin-toast">{notice}</div>}</section></main>
}
function Info({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="admin-panel"><span className="admin-kicker">{kicker}</span><h2>{title}</h2><p className="admin-help">{text}</p></div>}
