"use client";
import Image from "next/image";
import Link from "next/link";
import { createContext, useContext, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { usePathname } from "next/navigation";
import { Menu, X, Phone, MapPin, ArrowRight, Check, ShieldCheck, Network, Building2, House, Factory, ChevronRight } from "lucide-react";
import { catalog, commercialHome } from "@/lib/catalog";
import { Camera, BellRing, ScanFace, Wifi, LockKeyhole, DoorOpen, Cable, Server, Settings } from "lucide-react";
import SafeHtml from "./safe-html";

type Service = typeof catalog[number];
type Post={id:string;title:string;slug:string;excerpt:string;content:string;contentFormat?:"text"|"html";category:string;tags:string[];image:string;author:string;status:"draft"|"published"|"scheduled";publishAt:string;seoTitle:string;seoDescription:string};
type SiteCms={company:Record<string,string>;home:Record<string,string>;seo:Record<string,string>;services:Service[];posts:Post[]};
const defaultServices:Service[] = catalog;
const defaultSite:SiteCms={company:{name:"Monitore Sistemas Eletrônicos",phone:"(47) 3365-3287",address:"5ª Avenida, 185 — Vila Real",city:"Balneário Camboriú – SC",postalCode:"88330-260",cnpj:"07.034.637/0001-48"},home:commercialHome,seo:{},services:defaultServices,posts:[]};

const SiteContext=createContext(defaultSite);
function useSite(){return useContext(SiteContext)}
function phoneHref(phone:string){return `tel:${phone.replace(/\D/g,"").replace(/^(\d{10,11})$/,"+55$1")}`}


const WHATSAPP_NUMBER = "5547984054218";
function whatsappHref(message:string){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`}
function quoteMessage(source:string,service?:string){return [`Olá, equipe Monitore! Encontrei a Monitore pelo site www.monitorecbc.com.br. Origem: ${source}.`,`Gostaria de solicitar um orçamento${service?` para ${service}`:""}.`,"Podem me orientar sobre os próximos passos?"].join("\n")}
function pageContext(pathname:string,site:SiteCms){
 const parts=pathname.split("/").filter(Boolean);
 if(site.services.some(s=>s.slug===parts[0]))return `a página de ${site.services.find(s=>s.slug===parts[0])?.name}`;
 if(parts[0]==="solucoes"&&parts[1])return `a página de ${site.services.find(s=>s.slug===parts[1])?.name||parts[1]}`;
 if(parts[0]==="blog"&&parts[1])return `o artigo ${site.posts.find(p=>p.slug===parts[1])?.title||parts[1]}`;
 const labels:Record<string,string>={solucoes:"a lista de soluções",segmentos:"a página de segmentos",cidades:"a página de cidades",projetos:"a página de projetos",blog:"o blog",sobre:"a página sobre a Monitore",contato:"a página de contato"};
 return labels[parts[0]]||"a página inicial";
}
function QuoteLink({className,source,service,children}:{className:string;source:string;service?:string;children:ReactNode}){return <a className={className} href={whatsappHref(quoteMessage(source,service))} target="_blank" rel="noopener noreferrer">{children}</a>}

const nav = [["Soluções","/solucoes"],["Segmentos","/segmentos"],["Cidades","/cidades"],["Projetos","/projetos"],["Blog","/blog"],["Sobre","/sobre"],["Contato","/contato"]];

function Header(){const [open,setOpen]=useState(false);const context=pageContext(usePathname(),useSite());return <><header className="header"><Link href="/" className="brand"><Image src="/logo-monitore-nova.png" alt="Monitore Sistemas Eletrônicos" width={250} height={92} priority/></Link><nav>{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</nav><QuoteLink className="btn small" source={`o menu (${context})`}>Solicitar orçamento</QuoteLink><button className="menu" aria-expanded={open} aria-label={open?"Fechar menu":"Abrir menu"} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobile"><Image src="/logo-monitore-nova.png" alt="Monitore Sistemas Eletrônicos" width={230} height={85}/>{nav.map(([n,h])=><Link key={h} href={h} onClick={()=>setOpen(false)}>{n}<ChevronRight size={17}/></Link>)}<QuoteLink className="btn" source={`o menu móvel (${context})`}>Solicitar orçamento</QuoteLink></div>}</>}
function Footer(){const {company,services}=useSite();return <footer><div className="footer-grid"><div><Image src="/logo-monitore-nova.png" alt="Monitore Sistemas Eletrônicos" width={260} height={96}/><p>Segurança eletrônica, CFTV, controle de acesso facial e automação de portões em Balneário Camboriú.</p></div><div><strong>Serviços e produtos</strong>{services.map(s=><Link key={s.slug} href={`/${s.slug}`}>{s.name}</Link>)}</div><div><strong>Contato oficial</strong><a href={phoneHref(company.phone)}>{company.phone}</a><a href={whatsappHref(quoteMessage("o WhatsApp no rodapé"))} target="_blank" rel="noopener noreferrer">WhatsApp: (47) 98405-4218</a><span>{company.address}</span><span>{company.city}</span><span>CEP {company.postalCode}</span></div></div><div className="legal"><span>{company.name} • CNPJ {company.cnpj}</span><Link href="/contato">Solicitar atendimento</Link></div></footer>}
function CTA(){const context=pageContext(usePathname(),useSite());return <section className="cta"><div><span className="eyebrow light">Vamos conversar?</span><h2>Segurança, instalação ou peças: fale com a Monitore.</h2><p>Conte sua necessidade para a equipe da Monitore.</p></div><QuoteLink className="btn white" source={`a chamada final (${context})`}>Solicitar orçamento <ArrowRight size={18}/></QuoteLink></section>}
function ServiceCard({s}:{s:Service}){const context=pageContext(usePathname(),useSite());return <article className="service-card"><Link aria-label={`Conhecer ${s.name}`} href={`/${s.slug}`} className={`card-image ${s.image?"":"service-symbol"}`}>{s.image?<Image src={s.image} alt={s.name} fill sizes="(max-width: 720px) 100vw, 33vw"/>:<ServiceIcon service={s}/>}</Link><div className="card-copy"><span className="card-kicker">{s.kind === "produto" ? "Venda de produtos" : "Instalação e serviços"}</span><h3>{s.name}</h3><p>{s.desc}</p><ul>{s.benefits.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><div className="card-actions"><QuoteLink className="btn small" source={`o card de ${s.name} (${context})`} service={s.name}>Solicitar orçamento</QuoteLink><Link href={`/${s.slug}`} className="text-link">Ver detalhes <ArrowRight size={16}/></Link></div></div></article>}
function Hero(){const {home}=useSite();return <section className="hero"><Image src="/monitore-hero.jpg" alt="Câmeras e segurança eletrônica Monitore" fill priority/><div className="hero-overlay"/><div className="hero-copy"><span className="eyebrow light">Monitore CBC • Balneário Camboriú</span><h1>{home.title}</h1><p>{home.description}</p><div className="hero-actions"><Link className="btn" href="/contato#orcamento">Solicitar Orçamento</Link><QuoteLink className="btn ghost" source="a página inicial"><Phone size={18}/>Falar pelo WhatsApp</QuoteLink></div></div></section>}
function Home(){const {services}=useSite();return <><Hero/><section className="facts"><div><b>(47) 3365-3287</b><span>Telefone oficial</span></div><div><b>Vila Real</b><span>Balneário Camboriú</span></div><div><b>07.034.637/0001-48</b><span>CNPJ</span></div></section><section className="section"><span className="eyebrow">Soluções Monitore</span><h2>Proteção e tecnologia para cada necessidade.</h2><p className="lead">Instalação profissional, organização de CFTV e venda de materiais e peças. Escolha a solução e solicite um orçamento.</p><div className="services-grid">{services.map(s=><ServiceCard key={s.slug} s={s}/>)}</div><div className="center"><Link className="btn dark" href="/solucoes">Ver todas as soluções <ArrowRight size={18}/></Link></div></section><section className="split dark-section"><div><span className="eyebrow light">Soluções sob medida</span><h2>Um projeto começa pelo diagnóstico certo.</h2><p>Entendimento do imóvel, dos fluxos e das prioridades antes da proposta.</p><div className="steps">{[["01","Leitura do cenário"],["02","Projeto contextual"],["03","Execução orientada"]].map(([n,t])=><div key={n}><b>{n}</b><span>{t}</span></div>)}</div></div><div className="feature-image"><Image src="/services/cftv.jpg" alt="Sistema de câmeras de segurança" fill/></div></section><section className="section"><span className="eyebrow">Projetado para pessoas reais</span><h2>Segurança deve simplificar a rotina.</h2><div className="audiences">{[[Building2,"Condomínios","Gestão compartilhada"],[Factory,"Empresas","Continuidade operacional"],[House,"Residências","Proteção cotidiana"]].map(([Icon,t,s]:any)=><article key={t}><Icon/><span>{s}</span><h3>{t}</h3><p>Instalações e equipamentos conforme os acessos, o uso e as necessidades do imóvel.</p></article>)}</div></section><section className="local"><div className="feature-image"><Image src="/services/cftv.jpg" alt="Instalação profissional de CFTV" fill/></div><div><span className="eyebrow">Presença local confirmada</span><h2>Monitore em Balneário Camboriú.</h2><p>5ª Avenida, 185 — Vila Real<br/>Balneário Camboriú – SC<br/>CEP 88330-260</p><Link className="text-link" href="/cidades/balneario-camboriu">Conhecer a página local <ArrowRight size={16}/></Link></div></section><CTA/></>}
function Solutions(){const {services}=useSite();return <><PageHero title="Segurança eletrônica, CFTV e automação de portões." text="Encontre a solução adequada ao contexto do seu imóvel." image="/services/cftv.jpg"/><section className="section"><span className="eyebrow">Portfólio de soluções</span><h2>Instalações, organização de CFTV, materiais e peças.</h2><div className="services-grid">{services.map(s=><ServiceCard key={s.slug} s={s}/>)}</div></section><CTA/></>}
function PageHero({title,text,image,service}:{title:string;text:string;image:string;service?:Service}){return <section className="page-hero">{image?<Image src={image} alt="" fill priority sizes="100vw"/>:<div className="hero-service-icon">{service&&<ServiceIcon service={service}/>}</div>}<div className="hero-overlay"/><div><span className="eyebrow light">Monitore Sistemas Eletrônicos</span><h1>{title}</h1><p>{text}</p></div></section>}
function StandardPage({kind}:{kind:string}){const data:any={segmentos:["Soluções pensadas para cada contexto de decisão.","Residências, condomínios e empresas têm fluxos diferentes. A Monitore organiza cada projeto conforme a necessidade apresentada.","/services/interfonia.jpg"],sobre:["Monitore Sistemas Eletrônicos.","Atendimento a partir de Balneário Camboriú com foco em segurança eletrônica, CFTV, controle de acesso facial e automação de portões.","/services/cftv.jpg"],projetos:["Projetos organizados com contexto.","Converse com a equipe sobre a instalação que você precisa para sua casa, condomínio ou empresa.","/services/cftv.jpg"],cidades:["Segurança eletrônica em Balneário Camboriú.","Atendimento em Balneário Camboriú. Para outras localidades, consulte a equipe sobre disponibilidade.","/services/portoes.jpg"],blog:["Conteúdo que ajuda a decidir melhor.","Guias sobre câmeras, alarmes, controle de acesso e automação de portões, organizados para responder dúvidas antes da solicitação de orçamento.","/services/cftv.jpg"]};const [title,text,image]=data[kind];return <><PageHero title={title} text={text} image={image}/><section className="section"><div className="content-grid"><div><span className="eyebrow">Informação clara</span><h2>{kind==="sobre"?"Identidade, localização e compromisso.":"Atendimento conforme a necessidade do seu imóvel."}</h2><p className="lead">{text}</p><p>Telefone oficial: <a href="tel:+554733653287">(47) 3365-3287</a><br/>5ª Avenida, 185 — Vila Real, Balneário Camboriú – SC.</p><QuoteLink className="btn dark" source={`o conteúdo da página ${kind}`}>Solicitar orçamento</QuoteLink></div><div className="stack-images"><Image src={image} alt={title} fill/></div></div></section>{kind==="segmentos"&&<section className="section alt"><div className="audiences">{[[Building2,"Condomínios"],[Factory,"Empresas"],[House,"Residências"]].map(([Icon,t]:any)=><article key={t}><Icon/><h3>{t}</h3><p>Soluções organizadas conforme o uso e o ambiente.</p></article>)}</div></section>}{kind==="blog"&&<section className="section alt"><h2>Temas em preparação</h2><div className="post-grid">{["Como planejar um sistema de CFTV","Controle de acesso em condomínios","Rack e organização de CFTV"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Conteúdo editorial em preparação, sem alegações ainda não validadas.</p></article>)}</div></section>}<CTA/></>}
const serviceIcons: Record<string, typeof Camera> = {Camera,BellRing,Phone,ScanFace,Wifi,LockKeyhole,DoorOpen,Cable,Server,Settings};
function ServiceIcon({service}:{service:Service}){const Icon=serviceIcons[service.icon]||ShieldCheck;return <Icon aria-hidden="true"/>}
function ServicePage({slug}:{slug:string}){const {services}=useSite();const s=services.find(x=>x.slug===slug);if(!s)return null;const related=services.filter(x=>x.slug!==slug).slice(s.kind==="produto"?4:0,s.kind==="produto"?8:4);return <><PageHero title={`${s.name} em Balneário Camboriú`} text={s.desc} image={s.image} service={s}/><section className="section"><div className="content-grid"><div><span className="eyebrow">{s.kind==="produto"?"Venda de produtos":"Instalação e serviços"}</span><h2>{s.name}</h2><p className="lead">{s.desc}</p><h3>Benefícios para o seu projeto</h3><ul className="benefit-list">{s.benefits.map(x=><li key={x}><ShieldCheck/>{x}</li>)}</ul><h3>Como funciona</h3><p className="lead">{s.how}</p><h3>Onde utilizar</h3><p className="lead">Casas, condomínios, lojas, escritórios, empresas, galpões, indústrias e estacionamentos, conforme as condições do imóvel e a compatibilidade dos equipamentos.</p><h3>Atendimento Monitore</h3><p className="lead">Converse com a equipe em Balneário Camboriú para definir os equipamentos e o escopo do orçamento.</p><Link className="btn" href={`/contato?servico=${encodeURIComponent(s.name)}#orcamento`}>{s.kind==="produto"?"Quero Comprar Peças ou Materiais":"Solicitar Orçamento"}</Link></div><div className={s.image?"stack-images":"service-detail-symbol"}>{s.image?<Image src={s.image} alt={s.name} fill sizes="(max-width:720px) 100vw, 50vw"/>:<ServiceIcon service={s}/>}</div></div></section><section className="section alt"><h2>Perguntas frequentes</h2>{s.faq.map(f=><details className="faq" key={f.question}><summary>{f.question}</summary><p>{f.answer}</p></details>)}<QuoteLink className="btn" source={`a página ${s.name}`} service={s.name}>Solicitar Orçamento pelo WhatsApp</QuoteLink></section><section className="section"><h2>Solicite seu orçamento</h2><ContactForm initialInterest={s.name}/></section><section className="section alt"><h2>Soluções relacionadas</h2><div className="services-grid">{related.map(r=><ServiceCard key={r.slug} s={r}/>)}</div></section><CTA/></>}
function ContactForm({initialInterest=""}:{initialInterest?:string}){const {services}=useSite();const [interest,setInterest]=useState(initialInterest);useEffect(()=>{if(!initialInterest)setInterest(new URLSearchParams(window.location.search).get("servico")||"")},[initialInterest]);function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const message=["Olá, equipe Monitore! Solicitação pelo site www.monitorecbc.com.br.",...[["nome","Nome"],["telefone","WhatsApp"],["cidade","Cidade"],["cliente","Tipo de cliente"],["servico","Serviço de interesse"],["necessidade","Descrição"]].map(([key,label])=>`${label}: ${data.get(key)}`)].join("\n");window.location.assign(whatsappHref(message));}return <form onSubmit={submit}><label>Nome<input name="nome" required autoComplete="name"/></label><label>Telefone / WhatsApp<input name="telefone" type="tel" required autoComplete="tel"/></label><label>Cidade<input name="cidade" required defaultValue="Balneário Camboriú"/></label><label>Tipo de cliente<select name="cliente" required><option value="">Selecione</option>{["Residência","Condomínio","Comércio / Loja","Escritório","Empresa","Galpão / Indústria","Estacionamento"].map(x=><option key={x}>{x}</option>)}</select></label><label>Serviço de interesse<select name="servico" required value={interest} onChange={e=>setInterest(e.target.value)}><option value="">Selecione</option>{services.map(s=><option key={s.slug}>{s.name}</option>)}</select></label><label>Descrição do que precisa<textarea name="necessidade" required rows={4}/></label><button className="btn" type="submit">Solicitar Orçamento pelo WhatsApp</button><small>O WhatsApp abrirá com a solicitação preenchida. Confirme o envio na conversa.</small></form>}
function Contact(){const {company}=useSite();return <><PageHero title="Solicite um orçamento à Monitore." text="Instalações, materiais e peças para a sua necessidade." image="/services/interfonia.jpg"/><section className="section contact" id="orcamento"><div><span className="eyebrow">Fale com a equipe</span><h2>Conte o que você precisa.</h2><a className="contact-line" href={whatsappHref(quoteMessage("a página de contato"))}><Phone/>WhatsApp: (47) 98405-4218</a><a className="contact-line" href={phoneHref(company.phone)}><Phone/>{company.phone}</a><p>{company.address}<br/>{company.city} — CEP {company.postalCode}</p></div><ContactForm/></section></>}
export default function SitePage({slug=[],initialSite}:{slug?:string[];initialSite:SiteCms}){const pathname=usePathname();const now=Date.now();const site={...initialSite,services:initialSite.services.filter(s=>s.published!==false),posts:initialSite.posts.filter(p=>p.status==="published"||p.status==="scheduled"&&!!p.publishAt&&new Date(p.publishAt).getTime()<=now)};let content:ReactNode=<Home/>;if(slug.length===1&&site.services.some(s=>s.slug===slug[0]))content=<ServicePage slug={slug[0]}/>;else if(slug[0]==="solucoes")content=<Solutions/>;else if(slug[0]==="blog"&&slug[1])content=<BlogPostPage slug={slug[1]}/>;else if(slug[0]==="blog")content=<BlogPage/>;else if(["segmentos","sobre","projetos","cidades"].includes(slug[0]))content=<StandardPage kind={slug[0]}/>;else if(slug[0]==="contato")content=<Contact/>;return <SiteContext.Provider value={site}><Header/><main>{content}</main><Footer/><div className="mobile-cta"><a href={phoneHref(site.company.phone)}><Phone size={18}/>Ligar</a><QuoteLink className="" source={`a barra móvel (${pageContext(pathname,site)})`}>Orçamento</QuoteLink></div></SiteContext.Provider>}

function BlogPage(){const {posts}=useSite();return <><PageHero title="Conteúdo para decisões mais seguras." text="Guias sobre câmeras, alarmes, controle de acesso facial e automação de portões." image="/services/cftv.jpg"/><section className="section"><span className="eyebrow">Blog Monitore</span><h2>Informação para escolher sua solução de segurança.</h2>{posts.length?<div className="public-blog-grid">{posts.map(post=><article key={post.id}><Link href={`/blog/${post.slug}`} className="blog-cover" style={{backgroundImage:`url(${post.image||"/services/cftv.jpg"})`}} aria-label={`Ler ${post.title}`}/><div><span>{post.category||"Conteúdo Monitore"}</span><h3><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3><p>{post.excerpt}</p><small>{post.author}{post.publishAt?` • ${new Date(post.publishAt).toLocaleDateString("pt-BR")}`:""}</small><Link className="text-link" href={`/blog/${post.slug}`}>Ler artigo <ArrowRight size={16}/></Link></div></article>)}</div>:<div className="blog-empty-public"><BookOpenIcon/><h3>Novos conteúdos em preparação</h3><p>Os artigos serão publicados aqui após a validação da equipe Monitore.</p></div>}</section><CTA/></>}
function BlogPostPage({slug}:{slug:string}){const {posts}=useSite();const post=posts.find(p=>p.slug===slug);if(!post)return <BlogPage/>;return <><section className="blog-article-hero"><div className="blog-article-cover" style={{backgroundImage:`url(${post.image||"/services/cftv.jpg"})`}}/><div><span className="eyebrow light">{post.category||"Blog Monitore"}</span><h1>{post.title}</h1><p>{post.excerpt}</p><small>Por {post.author}{post.publishAt?` • ${new Date(post.publishAt).toLocaleDateString("pt-BR")}`:""}</small></div></section><article className="blog-article"><div className="blog-tags">{post.tags.map(tag=><span key={tag}>{tag}</span>)}</div>{post.contentFormat==="html"?<SafeHtml html={post.content}/>:post.content.split(/\n+/).filter(Boolean).map((paragraph,i)=><p key={i}>{paragraph}</p>)}<div className="blog-share"><b>Precisa de uma solução para o seu imóvel?</b><QuoteLink className="btn" source={`o artigo ${post.title}`}>Solicitar orçamento</QuoteLink></div></article><CTA/></>}
function BookOpenIcon(){return <svg viewBox="0 0 24 24" width="38" height="38" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M2 4h6a4 4 0 0 1 4 4v12a4 4 0 0 0-4-4H2z"/><path d="M22 4h-6a4 4 0 0 0-4 4v12a4 4 0 0 1 4-4h6z"/></svg>}
